version: "3.5"
services:
  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=mysql
    depends_on:
      - mysql
  php:
      build:
        context: .
        dockerfile: php/Dockerfile
        args:
          - LOCAL_UID=${LOCAL_UID}
          - LOCAL_GID=${LOCAL_GID}
      volumes:
          - ./php/virtualHost.conf:/etc/apache2/sites-enabled/000-a.conf
          - ${WORDPRESS_PATH}:/application
          - ./var:/application/var
      depends_on:
      - mysql
      ports:
          - "80:80"